mongo:
  host: localhost
  port: 27017

neo4j:
  host: localhost
  port: 7687

mcp:
  host: localhost
  port: 8000

rag_enabled: true

unified_metadata:
  - title
  - section
  - subsection

models:
  provider: bedrock
  embedding: amazon.titan-embed-text-v2:0
  llm: amazon.nova-lite-v1:0
