ollama:
  host: ollama-container
  port: 11434

mongo:
  host: mongodb-container
  port: 27017

neo4j:
  host: neo4j-container
  port: 7687

mcp:
  host: mcp-container
  port: 8000

rag_enabled: true

unified_metadata:
  - title
  - section
  - subsection

models:
  provider: bedrock
  embedding: amazon.titan-embed-text-v2:0
  llm: amazon.nova-lite-v1:0
