services:
  neo4j:
    image: neo4j:5.26.5
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./.neo4j/logs:/logs
      - ./.neo4j/config:/config
      - ./.neo4j/data:/data
      - ./.neo4j/plugins:/plugins
    networks:
      - internal

  mongo:
    image: mongo:8.0.6
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - internal

networks:
  internal:
    driver: bridge
