services:
  app:
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app/src
      - DEBUG=1
    command: ["uv", "run", "fastapi", "dev", "src/serka/main.py", "--host", "0.0.0.0", "--port", "8000"]

  chromadb:
    extends:
      file: docker-compose.yml
      service: chromadb
    ports:
      - "8000:8000"

  ollama:
    extends:
      file: docker-compose.yml
      service: ollama
    ports:
      - "11434:11434"

  mongodb:
    ports:
      - "27017:27017"
