name: Run unit tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install uv
        uv sync
    - name: Test with pytest
      id: tests
      run: uv run pytest --cov==src
    - id: coverage
      run: echo "${{ steps.tests.outputs.data }}" | grep TOTAL | awk "{print $NF}"
    - name: Generate coverage badge
      run: |
        pip install setuptools pybadges
        python -m pybadges --left-text=coverage --right-text=${{ steps.coverage.outputs.data }} > coverage-badge.svg
    - name: Upload coverage badge
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: coverage-badge.svg
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: coverage-badge.svg
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
